[book]
title = "Die Programmiersprache Rust"
authors = ["Steve Klabnik", "Carol Nichols", "Chris Krycho", "unter Mitarbeit der Rust-Gemeinschaft"]
description = "Eine deutsche Gemeinschafts-Übersetzung des offiziellen Rust-Buchs."
language = "de"

[output.html]
additional-css = ["theme/ferris.css", "theme/2018-edition.css", "theme/semantic-notes.css", "theme/listing.css"]
additional-js = ["theme/ferris.js"]
git-repository-url = "https://github.com/rust-lang-de/rustbook-de"

[rust]
edition = "2024"
